name = "pagest"
main = "functions/worker.js"
compatibility_date = "2025-07-25"

[assets]
directory = "./src"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = false
