name = "my-spa-worker"
compatibility_date = "2025-07-25"
main = "src/index.js"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
binding = "ASSETS"
run_worker_first = [ "/api/*" ]
