name = "pagest"
main = "src/index.js"
compatibility_date = "2025-07-25"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = false  # ✅ must be boolean here
