name = "pagest"
main = "functions/worker.js"
compatibility_date = "2025-07-25"
compatibility_flags = [ "global_fetch_strictly_public" ]

[build]
command = "npm run build"

[assets]
directory = "./src"
