name = "pagest"
compatibility_date = "2025-07-25"

main = "functions/worker.js"

[assets]
directory = "./src"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]
